server:
  port: 8080

spring:
  application:
    name: accounts
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071
  datasource:
    url: jdbc:h2:file:/tmp/bank;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: accounts
    description: JMO Devel Accounts Microservice
    version: 3.0.1-SNAPSHOT

logging:
  level:
    com:
      jmo:
        devel:
          accounts: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 # requests monitored initially
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50 # from open to close
      waitDurationInOpenState: 10000

resilience4j.rety:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2 # 1st 100ms, 2nd 200ms
      ignoreExceptions: # do not retry if this exception is thrown. fallback is called immediately
      - java.lang.NullPointerException
      retryExceptions: # retry if this exception is thrown. ignoreExceptions is ignored
      - java.util.concurrent.TimeoutException
