server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        native:
          #search-locations: classpath:/config
          search-locations: file:///tmp/config
        git:
          uri: https://github.com/jmodevel/springcloud-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: Sk1PIERldmVsIGptby5kZXZlbEBnbWFpbC5jb20

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true