server:
  port: 8081
spring:
  application:
    name: loans
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always # execute schema.sql

# allows to invoke /actuator/refresh to refresh config
management:
  endpoints:
    web:
      exposure:
        include: "*"