spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          # connect with Eureka Server and locate details about MS
          #   and forward traffic from external clients to MS
          # false: do not allow /accounts/ requests to be handled by gateway
          #   only the ones defined by RouteLocator
          # true: /accounts/api/fetch will work without any other config
          enabled: false
          # accept service with service only in lower case
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000 # time gateway is going to take to get a connection thread from the other MS
        response-timeout: 2s # maximum time gateway is going to wait for a response from MS
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: gateway-server
    description: JMO Devel Gateway Server
    version: 3.0.1-SNAPSHOT

logging:
  level:
    com:
      jmo:
        devel:
          gateway: DEBUG

resilience4j.circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10 # requests monitored initially
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50 # from open to close
        waitDurationInOpenState: 10000